# Set up navigation: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
site_name: mllibs
site_url: https://github.com/shtrausslearning/shtrausslearning.github.io
repo_name: 'mllibs'
repo_url: https://github.com/shtrausslearning/mllibs
edit_uri: tree/master/docs/src/markdown
site_description: Reference for mllibs
docs_dir: markdown

##################################################################

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



##################################################################

theme:
    name: material
    icon:
        logo: fontawesome/solid/code 
        repo: fontawesome/brands/github
    language: en
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.sections
        # - navigation.expand
        - navigation.tracking
        - navigation.top
        - content.tabs.link

    palette:
        - scheme: slate

    font:
        text: Roboto
        code: Roboto Mono

extra:
    manifest: manifest.webmanifest
    social:

plugins:
    - search
    - tags
    - offline

copyright: |
  Copyright &copy; 2023 <a href="https://github.com/shtrausslearning"  target="_blank" rel="noopener">Andrey Shtrauss</a>

nav:
- Home: home.md

- Installation: install.md

- Modules: 
    - Available modules: modules/list.md
    - Adding new modules: modules/adding.md
    - Grouping modules: modules/grouping.md

- Tutorials: 
    - Overview: tutorials/overview.md

- Documentation: 
    - nlpm: documentation/nlpm.md
    - nlpi: documentation/nlpi.md

- Group:
    - Task Status: group/status.md
    - Meetings: group/meetups.md
    - Members: group/members.md
