# Set up navigation: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
site_name: mllibs
site_url: https://github.com/shtrausslearning/shtrausslearning.github.io
repo_name: 'mllibs'
repo_url: https://github.com/shtrausslearning/mllibs
edit_uri: tree/master/docs/src/markdown
site_description: Reference for mllibs
docs_dir: markdown

##################################################################

markdown_extensions:
    - markdown.extensions.toc:
        slugify: !!python/name:pymdownx.slugs.uslugify
        permalink: ""
    - markdown.extensions.admonition:
    - markdown.extensions.smarty:
        smart_quotes: false
    - pymdownx.betterem:
    - markdown.extensions.attr_list:
    - markdown.extensions.def_list:
    - markdown.extensions.tables:
    - markdown.extensions.abbr:
    - markdown.extensions.footnotes:
    - markdown.extensions.md_in_html:
    - pymdownx.highlight:
        extend_pygments_lang:
          - name: php-inline
            lang: php
            options:
              startinline: true
          - name: pycon3
            lang: pycon
            options:
              python3: true
        linenums_style: pymdownx-inline
    - pymdownx.inlinehilite:
        custom_inline:
          - name: math
            class: arithmatex
            format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
    - pymdownx.magiclink:
        repo_url_shortener: true
        repo_url_shorthand: true
        social_url_shorthand: true
        social_url_shortener: true
        user: facelessuser
        repo: pymdown-extensions
    - pymdownx.tilde:
    - pymdownx.caret:
    - pymdownx.smartsymbols:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.escapeall:
        hardbreak: True
        nbsp: True
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.progressbar:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.mark:
    # - pymdownx.striphtml:
    - pymdownx.snippets:
        base_path: markdown/_snippets
    - pymdownx.keys:
        separator: "\uff0b"
    - pymdownx.details:
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true

##################################################################

theme:
    name: material
    icon:
        logo: fontawesome/solid/code 
        repo: fontawesome/brands/github
    language: en
    features:
        # Navigation settings
        - navigation.instant
        - navigation.instant.progress
        - navigation.sections
        - navigation.expand
        - navigation.tracking
        - navigation.top
        - content.tabs.link

    palette:
        - scheme: slate
          # primary: gold
          # accent: gold

    font:
        text: Roboto
        code: Roboto Mono

extra:
    manifest: manifest.webmanifest
    social:

plugins:
    - search
    - tags
    - offline

copyright: |
  Copyright &copy; 2023 <a href="https://github.com/shtrausslearning"  target="_blank" rel="noopener">Andrey Shtrauss</a>

nav:
- Home: home.md
- Meetings: meetups.md
